"""Add public_id, created_at, updated_at to Ingredient

Revision ID: 0861453c8179
Revises: 8785524125bd
Create Date: 2026-07-27 12:23:44.390837

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import uuid

# revision identifiers, used by Alembic.
revision: str = "0861453c8179"
down_revision: Union[str, Sequence[str], None] = "8785524125bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add public_id as nullable first, so existing rows aren't a problem yet
    op.add_column("ingredients", sa.Column("public_id", sa.UUID(), nullable=True))
    op.add_column(
        "ingredients",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "ingredients",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    # 2. Backfill public_id for existing rows
    connection = op.get_bind()
    ingredients_table = sa.table(
        "ingredients", sa.column("id", sa.Integer), sa.column("public_id", sa.UUID)
    )
    result = connection.execute(sa.select(ingredients_table.c.id))
    for row in result:
        connection.execute(
            ingredients_table.update()
            .where(ingredients_table.c.id == row.id)
            .values(public_id=uuid.uuid4())
        )

    # 3. Now that every row has a value, enforce NOT NULL
    op.alter_column("ingredients", "public_id", nullable=False)

    op.create_index(
        op.f("ix_ingredients_public_id"), "ingredients", ["public_id"], unique=True
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingredients_public_id"), table_name="ingredients")
    op.drop_column("ingredients", "updated_at")
    op.drop_column("ingredients", "created_at")
    op.drop_column("ingredients", "public_id")
    # ### end Alembic commands ###
