"""Added public id in user and updated_at

Revision ID: 23b312814d03
Revises: 2fe9bd07e76e
Create Date: 2026-07-28 14:27:29.817635

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision: str = "23b312814d03"
down_revision: Union[str, Sequence[str], None] = "2fe9bd07e76e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shopping_lists",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column("users", sa.Column("public_id", sa.UUID(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # 2. Backfill public_id for existing rows
    connection = op.get_bind()
    user_table = sa.table(
        "users", sa.column("id", sa.Integer), sa.column("public_id", sa.UUID)
    )
    result = connection.execute(sa.select(user_table.c.id))
    for row in result:
        connection.execute(
            user_table.update()
            .where(user_table.c.id == row.id)
            .values(public_id=uuid.uuid4())
        )

    # 3. Now that every row has a value, enforce NOT NULL
    op.alter_column("users", "public_id", nullable=False)

    op.create_index(op.f("ix_users_public_id"), "users", ["public_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_public_id"), table_name="users")
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("users", "updated_at")
    op.drop_column("users", "public_id")
    op.alter_column(
        "shopping_lists",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
