"""Add public_id, created_at, updated_at to shopping lists

Revision ID: 2fe9bd07e76e
Revises: a14393c29e7a
Create Date: 2026-07-28 08:20:32.474957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import uuid

# revision identifiers, used by Alembic.
revision: str = "2fe9bd07e76e"
down_revision: Union[str, Sequence[str], None] = "a14393c29e7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shopping_lists", sa.Column("public_id", sa.UUID(), nullable=True))
    op.add_column(
        "shopping_lists",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.alter_column(
        "shopping_lists",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )

    # 2. Backfill public_id for existing rows
    connection = op.get_bind()
    shopping_list_table = sa.table(
        "shopping_lists", sa.column("id", sa.Integer), sa.column("public_id", sa.UUID)
    )
    result = connection.execute(sa.select(shopping_list_table.c.id))
    for row in result:
        connection.execute(
            shopping_list_table.update()
            .where(shopping_list_table.c.id == row.id)
            .values(public_id=uuid.uuid4())
        )

    # 3. Now that every row has a value, enforce NOT NULL
    op.alter_column("shopping_lists", "public_id", nullable=False)

    op.create_index(
        op.f("ix_shopping_lists_public_id"),
        "shopping_lists",
        ["public_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shopping_lists_public_id"), table_name="shopping_lists")
    op.alter_column(
        "shopping_lists",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("shopping_lists", "updated_at")
    op.drop_column("shopping_lists", "public_id")
    # ### end Alembic commands ###
