"""initial schema

Revision ID: 38a70f4f8fce
Revises: 
Create Date: 2026-08-03 13:14:32.163033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a70f4f8fce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('shopping_category', sa.String(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'user_id', name='uq_ingredient_name_per_user')
    )
    op.create_index(op.f('ix_ingredients_public_id'), 'ingredients', ['public_id'], unique=True)
    op.create_index('ix_ingredients_user_id_name', 'ingredients', ['user_id', 'name'], unique=False)
    op.create_table('shopping_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_lists_public_id'), 'shopping_lists', ['public_id'], unique=True)
    op.create_index('ix_shopping_lists_user_id_id', 'shopping_lists', ['user_id', 'id'], unique=False)
    op.create_table('weekly_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_plans_public_id'), 'weekly_plans', ['public_id'], unique=True)
    op.create_index('ix_weekly_plans_user_id_id', 'weekly_plans', ['user_id', 'id'], unique=False)
    op.create_index('uq_one_default_weekly_plan_per_user', 'weekly_plans', ['is_default', 'user_id'], unique=True, postgresql_where=sa.text('is_default = true'))
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('main_ingredient_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['main_ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dishes_main_ingredient_id', 'dishes', ['main_ingredient_id'], unique=False)
    op.create_index(op.f('ix_dishes_public_id'), 'dishes', ['public_id'], unique=True)
    op.create_index('ix_dishes_user_id_id', 'dishes', ['user_id', 'id'], unique=False)
    op.create_table('shopping_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopping_list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('shopping_category', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shopping_list_items_ingredient_id', 'shopping_list_items', ['ingredient_id'], unique=False)
    op.create_index('ix_shopping_list_items_shopping_list_id', 'shopping_list_items', ['shopping_list_id'], unique=False)
    op.create_table('weekly_plan_dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('weekly_plan_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weekly_plan_dishes_dish_id', 'weekly_plan_dishes', ['dish_id'], unique=False)
    op.create_index('ix_weekly_plan_dishes_weekly_plan_id', 'weekly_plan_dishes', ['weekly_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weekly_plan_dishes_weekly_plan_id', table_name='weekly_plan_dishes')
    op.drop_index('ix_weekly_plan_dishes_dish_id', table_name='weekly_plan_dishes')
    op.drop_table('weekly_plan_dishes')
    op.drop_index('ix_shopping_list_items_shopping_list_id', table_name='shopping_list_items')
    op.drop_index('ix_shopping_list_items_ingredient_id', table_name='shopping_list_items')
    op.drop_table('shopping_list_items')
    op.drop_index('ix_dishes_user_id_id', table_name='dishes')
    op.drop_index(op.f('ix_dishes_public_id'), table_name='dishes')
    op.drop_index('ix_dishes_main_ingredient_id', table_name='dishes')
    op.drop_table('dishes')
    op.drop_index('uq_one_default_weekly_plan_per_user', table_name='weekly_plans', postgresql_where=sa.text('is_default = true'))
    op.drop_index('ix_weekly_plans_user_id_id', table_name='weekly_plans')
    op.drop_index(op.f('ix_weekly_plans_public_id'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_index('ix_shopping_lists_user_id_id', table_name='shopping_lists')
    op.drop_index(op.f('ix_shopping_lists_public_id'), table_name='shopping_lists')
    op.drop_table('shopping_lists')
    op.drop_index('ix_ingredients_user_id_name', table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_public_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
