"""add composite indexes, drop redundant pk indexes

Revision ID: 456ae502bd34
Revises: 23b312814d03
Create Date: 2026-07-30 13:32:22.286329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456ae502bd34'
down_revision: Union[str, Sequence[str], None] = '23b312814d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dishes_id'), table_name='dishes')
    op.create_index('ix_dishes_main_ingredient_id', 'dishes', ['main_ingredient_id'], unique=False)
    op.create_index('ix_dishes_user_id_id', 'dishes', ['user_id', 'id'], unique=False)
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.create_index('ix_ingredients_user_id_name', 'ingredients', ['user_id', 'name'], unique=False)
    op.drop_index(op.f('ix_shopping_list_items_id'), table_name='shopping_list_items')
    op.create_index('ix_shopping_list_items_ingredient_id', 'shopping_list_items', ['ingredient_id'], unique=False)
    op.create_index('ix_shopping_list_items_shopping_list_id', 'shopping_list_items', ['shopping_list_id'], unique=False)
    op.drop_index(op.f('ix_shopping_lists_id'), table_name='shopping_lists')
    op.create_index('ix_shopping_lists_user_id_id', 'shopping_lists', ['user_id', 'id'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_weekly_plan_id'), table_name='weekly_plan')
    op.create_index('ix_weekly_plan_user_id_id', 'weekly_plan', ['user_id', 'id'], unique=False)
    op.drop_index(op.f('ix_weekly_plan_dish_id'), table_name='weekly_plan_dish')
    op.create_index('ix_weekly_plan_dish_dish_id', 'weekly_plan_dish', ['dish_id'], unique=False)
    op.create_index('ix_weekly_plan_dish_weekly_plan_id', 'weekly_plan_dish', ['weekly_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weekly_plan_dish_weekly_plan_id', table_name='weekly_plan_dish')
    op.drop_index('ix_weekly_plan_dish_dish_id', table_name='weekly_plan_dish')
    op.create_index(op.f('ix_weekly_plan_dish_id'), 'weekly_plan_dish', ['id'], unique=False)
    op.drop_index('ix_weekly_plan_user_id_id', table_name='weekly_plan')
    op.create_index(op.f('ix_weekly_plan_id'), 'weekly_plan', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index('ix_shopping_lists_user_id_id', table_name='shopping_lists')
    op.create_index(op.f('ix_shopping_lists_id'), 'shopping_lists', ['id'], unique=False)
    op.drop_index('ix_shopping_list_items_shopping_list_id', table_name='shopping_list_items')
    op.drop_index('ix_shopping_list_items_ingredient_id', table_name='shopping_list_items')
    op.create_index(op.f('ix_shopping_list_items_id'), 'shopping_list_items', ['id'], unique=False)
    op.drop_index('ix_ingredients_user_id_name', table_name='ingredients')
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.drop_index('ix_dishes_user_id_id', table_name='dishes')
    op.drop_index('ix_dishes_main_ingredient_id', table_name='dishes')
    op.create_index(op.f('ix_dishes_id'), 'dishes', ['id'], unique=False)
    # ### end Alembic commands ###
