"""Add public_id, created_at, updated_at to Dishes

Revision ID: 62e9bf4eab2c
Revises: 0861453c8179
Create Date: 2026-07-27 13:34:40.351173

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import uuid

# revision identifiers, used by Alembic.
revision: str = "62e9bf4eab2c"
down_revision: Union[str, Sequence[str], None] = "0861453c8179"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dishes", sa.Column("public_id", sa.UUID(), nullable=True))

    op.add_column(
        "dishes",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "dishes",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # 2. Backfill public_id for existing rows
    connection = op.get_bind()
    dishes_table = sa.table(
        "dishes", sa.column("id", sa.Integer), sa.column("public_id", sa.UUID)
    )
    result = connection.execute(sa.select(dishes_table.c.id))
    for row in result:
        connection.execute(
            dishes_table.update()
            .where(dishes_table.c.id == row.id)
            .values(public_id=uuid.uuid4())
        )

    # 3. Now that every row has a value, enforce NOT NULL
    op.alter_column("dishes", "public_id", nullable=False)

    op.create_index(op.f("ix_dishes_public_id"), "dishes", ["public_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dishes_public_id"), table_name="dishes")
    op.drop_column("dishes", "updated_at")
    op.drop_column("dishes", "created_at")
    op.drop_column("dishes", "public_id")
    # ### end Alembic commands ###
