"""Simplify Dish model - remove main_category

Revision ID: 76e93239cc81
Revises: 26270f315c59
Create Date: 2026-07-01 14:26:32.300168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e93239cc81'
down_revision: Union[str, Sequence[str], None] = '26270f315c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dishes', 'main_ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('dishes', 'main_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('main_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('dishes', 'main_ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
