"""Add WeeklyPlan and WeeklyPlanDish models

Revision ID: 7c486d56b426
Revises: 76e93239cc81
Create Date: 2026-07-02 12:05:45.834647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c486d56b426'
down_revision: Union[str, Sequence[str], None] = '76e93239cc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_plan_id'), 'weekly_plan', ['id'], unique=False)
    op.create_index('uq_one_default_weekly_plan', 'weekly_plan', ['is_default'], unique=True, postgresql_where=sa.text('is_default = true'))
    op.create_table('weekly_plan_dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('weekly_plan_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_plan_dish_id'), 'weekly_plan_dish', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_plan_dish_id'), table_name='weekly_plan_dish')
    op.drop_table('weekly_plan_dish')
    op.drop_index('uq_one_default_weekly_plan', table_name='weekly_plan', postgresql_where=sa.text('is_default = true'))
    op.drop_index(op.f('ix_weekly_plan_id'), table_name='weekly_plan')
    op.drop_table('weekly_plan')
    # ### end Alembic commands ###
