"""Add public_id, created_at, updated_at to weekly plans

Revision ID: a14393c29e7a
Revises: 62e9bf4eab2c
Create Date: 2026-07-28 07:26:15.479562

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import uuid

# revision identifiers, used by Alembic.
revision: str = "a14393c29e7a"
down_revision: Union[str, Sequence[str], None] = "62e9bf4eab2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("weekly_plan", sa.Column("public_id", sa.UUID(), nullable=True))
    op.add_column(
        "weekly_plan",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "weekly_plan",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    # 2. Backfill public_id for existing rows
    connection = op.get_bind()
    weekly_plan_table = sa.table(
        "weekly_plan", sa.column("id", sa.Integer), sa.column("public_id", sa.UUID)
    )
    result = connection.execute(sa.select(weekly_plan_table.c.id))
    for row in result:
        connection.execute(
            weekly_plan_table.update()
            .where(weekly_plan_table.c.id == row.id)
            .values(public_id=uuid.uuid4())
        )

    # 3. Now that every row has a value, enforce NOT NULL
    op.alter_column("weekly_plan", "public_id", nullable=False)

    op.create_index(
        op.f("ix_weekly_plan_public_id"), "weekly_plan", ["public_id"], unique=True
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weekly_plan_public_id"), table_name="weekly_plan")
    op.drop_column("weekly_plan", "updated_at")
    op.drop_column("weekly_plan", "created_at")
    op.drop_column("weekly_plan", "public_id")
    # ### end Alembic commands ###
