"""Add unique constraint on ingredient name

Revision ID: a8689247b48c
Revises: 7c486d56b426
Create Date: 2026-07-06 07:43:06.667882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8689247b48c'
down_revision: Union[str, Sequence[str], None] = '7c486d56b426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ingredients', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients', type_='unique')
    # ### end Alembic commands ###
